CREATE DATABASE [InventoryDB]
GO

USE [InventoryDB]
GO


SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Product_Master](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ITEM_NAME] [nvarchar](250) NOT NULL UNIQUE,
	[DESCRIPTION] [nvarchar](1000) NULL,
	[PRICE] [float] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


